### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by jamesls** [aws-samples/smithy-server-generator-typescript-sample#3]
I was following the instructions on the blog post [here](https://aws.amazon.com/blogs/devops/smithy-server-and-client-generator-for-typescript/), and I ran into an error that I don't understand when I try to run `./gradlew build`:

```
/tmp/test $ gh repo clone jamesls/smithy-server-generator-typescript-sample
Cloning into 'smithy-server-generator-typescript-sample'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 64 (delta 7), reused 53 (delta 6), pack-reused 0
Receiving objects: 100% (64/64), 1010.81 KiB | 13.30 MiB/s, done.
Resolving deltas: 100% (7/7), done.

/tmp/test $ cd smithy-server-generator-typescript-sample/

/tmp/test/smithy-server-generator-typescript-sample (main u=) $ ./gradlew build
Building Smithy model sources: [/private/tmp/test/smithy-server-generator-typescript-sample/model/src/main/smithy]
Loading Smithy configs: [/private/tmp/test/smithy-server-generator-typescript-sample/model/smithy-build.json]
WARNING: aws.protocols#ChecksumAlgorithmSet (Set)
     @ jar:file:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-aws-traits/1.19.0/349daa27967212b9292d92d264a4f77880b2efbd/smithy-aws-traits-1.19.0.jar!/META-INF/smithy/aws.protocols.json
     |
 266 |         "aws.protocols#ChecksumAlgorithmSet": {
     |                                               ^
     = Set shapes are deprecated and will be removed in Smithy IDL v2. Use a list shape with the @uniqueItems trait instead.



> Task :model:smithyBuildJar FAILED
Running smithy build
'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'

> Configure project :server-codegen
(detected Smithy CLI version 1.19.0)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':model:smithyBuildJar'.
> 'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 881ms
1 actionable task: 1 executed

```

<details>
  <summary><strong>Stack trace/logs if it helps</strong></summary>

  ```
Initialized native services in: /Users/jamessar/.gradle/native
Initialized jansi services in: /Users/jamessar/.gradle/native
Found daemon DaemonInfo{pid=53313, address=[8e1bc5ab-4fff-4fa5-a8b4-fb4444c8544e port:64154, addresses:[/127.0.0.1]], state=Idle, lastBusy=1656708773115, context=DefaultDaemonContext[uid=15279d15-0c73-4434-82f6-7c891c8303cb,javaHome=/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home,daemonRegistryDir=/Users/jamessar/.gradle/daemon,pid=53313,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} however its context does not match the desired criteria.
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home,daemonRegistryDir=/Users/jamessar/.gradle/daemon,pid=54561,idleTimeout=null,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=15279d15-0c73-4434-82f6-7c891c8303cb,javaHome=/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home,daemonRegistryDir=/Users/jamessar/.gradle/daemon,pid=53313,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 53786). The daemon log file: /Users/jamessar/.gradle/daemon/7.4.2/daemon-53786.out.log
Starting 8th build in daemon [uptime: 8 mins 56.814 secs, performance: 99%, non-heap usage: 34% of 256 MiB]
Using 12 worker leases.
Now considering [/private/tmp/test/smithy-server-generator-typescript-sample, /private/tmp/test/smithy-server-generator-typescript-sample/model, /private/tmp/smithy-server-generator-typescript-sample/model, /private/tmp/smithy-server-generator-typescript-sample] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file '/private/tmp/test/smithy-server-generator-typescript-sample/settings.gradle'.
Now considering [/private/tmp/test/smithy-server-generator-typescript-sample/model, /private/tmp/test/smithy-server-generator-typescript-sample, /private/tmp/smithy-server-generator-typescript-sample/model, /private/tmp/smithy-server-generator-typescript-sample] as hierarchies to watch
Projects loaded. Root project using build file '/private/tmp/test/smithy-server-generator-typescript-sample/build.gradle'.
Included projects: [root project 'string-wizard-service', project ':server-codegen', project ':typescript-client-codegen']

> Configure project :model
Evaluating project ':model' using build file '/private/tmp/test/smithy-server-generator-typescript-sample/model/build.gradle'.
Registering project ':model' in composite build. Will substitute for module 'software.amazon.smithy.demo:string-wizard-model'.

> Configure project :
Evaluating root project 'string-wizard-service' using build file '/private/tmp/test/smithy-server-generator-typescript-sample/build.gradle'.
:model:compileJava (Thread[Execution worker for ':model',5,main]) started.

> Task :model:compileJava NO-SOURCE
Skipping task ':model:compileJava' as it has no source files and no previous output files.
:model:compileJava (Thread[Execution worker for ':model',5,main]) completed. Took 0.002 secs.
:model:smithyBuildJar (Thread[Execution worker for ':model',5,main]) started.
Building Smithy model sources: [/private/tmp/test/smithy-server-generator-typescript-sample/model/src/main/smithy]
Loading Smithy configs: [/private/tmp/test/smithy-server-generator-typescript-sample/model/smithy-build.json]
Output directory set to: /private/tmp/test/smithy-server-generator-typescript-sample/model/build/smithyprojections/string-wizard-model
Error executing Smithy CLI (ReflectiveOperationException)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at software.amazon.smithy.gradle.SmithyUtils.lambda$executeCliThread$2(SmithyUtils.java:302)
Caused by: java.lang.NoSuchMethodError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$createValidator$2(ModelValidator.java:204)
	at software.amazon.smithy.model.loader.ModelAssembler.validate(ModelAssembler.java:639)
	at software.amazon.smithy.model.loader.ModelAssembler.assemble(ModelAssembler.java:556)
	at software.amazon.smithy.cli.commands.CommandUtils.buildModel(CommandUtils.java:78)
	at software.amazon.smithy.cli.commands.BuildCommand.execute(BuildCommand.java:112)
	at software.amazon.smithy.cli.Cli.run(Cli.java:144)
	at software.amazon.smithy.cli.SmithyCli.run(SmithyCli.java:91)
	at software.amazon.smithy.cli.SmithyCli.run(SmithyCli.java:82)
	... 4 more
Caused by: java.lang.NoSuchMethodError: 'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validateTrait(TraitBreakingChangesValidator.java:44)
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validate(TraitBreakingChangesValidator.java:36)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$createValidator$0(ModelValidator.java:198)
WARNING: aws.protocols#ChecksumAlgorithmSet (Set)
     @ jar:file:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-aws-traits/1.19.0/349daa27967212b9292d92d264a4f77880b2efbd/smithy-aws-traits-1.19.0.jar!/META-INF/smithy/aws.protocols.json
     |
 266 |         "aws.protocols#ChecksumAlgorithmSet": {
     |                                               ^
     = Set shapes are deprecated and will be removed in Smithy IDL v2. Use a list shape with the @uniqueItems trait instead.



> Task :model:smithyBuildJar FAILED
Caching disabled for task ':model:smithyBuildJar' because:
  Build cache is disabled
Task ':model:smithyBuildJar' is not up-to-date because:
  Task has failed previously.
Running smithy build
Skipping source that does not exist: /private/tmp/test/smithy-server-generator-typescript-sample/model/model
Skipping source that does not exist: /private/tmp/test/smithy-server-generator-typescript-sample/model/src/main/resources/META-INF/smithy
Configuring SmithyBuild classpaths for the `source` projection
Smithy CLI classpath already has the CLI in it
Executing Smithy CLI in a thread: build --discover-classpath /Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-aws-traits/1.19.0/349daa27967212b9292d92d264a4f77880b2efbd/smithy-aws-traits-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-validation-model/1.19.0/1cfcd747244e6691aefb6214f1826255a61e12a6/smithy-validation-model-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-cli/1.19.0/54eda7e44be670a1f8dc85a0291eac3124c4aefd/smithy-cli-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-build/1.19.0/f14ac93e7b4ffb1342362397f235edd1c3a90ca6/smithy-build-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-linters/1.19.0/41e24e511e96251eca990d187227b60277e1b0f3/smithy-linters-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-diff/1.19.0/b6482393ac1e09831c0abea07fc1eb67016559c8/smithy-diff-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-model/1.19.0/c0c13b04c565e4adef09c613ea0ffa6bf348050a/smithy-model-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-utils/1.19.0/2d84332b75c9700d9c00c1f5e9408d439115ab80/smithy-utils-1.19.0.jar --config /private/tmp/test/smithy-server-generator-typescript-sample/model/smithy-build.json --output /private/tmp/test/smithy-server-generator-typescript-sample/model/build/smithyprojections/string-wizard-model /private/tmp/test/smithy-server-generator-typescript-sample/model/src/main/smithy; using classpath /Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-aws-traits/1.19.0/349daa27967212b9292d92d264a4f77880b2efbd/smithy-aws-traits-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-validation-model/1.19.0/1cfcd747244e6691aefb6214f1826255a61e12a6/smithy-validation-model-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-cli/1.19.0/54eda7e44be670a1f8dc85a0291eac3124c4aefd/smithy-cli-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-build/1.19.0/f14ac93e7b4ffb1342362397f235edd1c3a90ca6/smithy-build-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-linters/1.19.0/41e24e511e96251eca990d187227b60277e1b0f3/smithy-linters-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-diff/1.19.0/b6482393ac1e09831c0abea07fc1eb67016559c8/smithy-diff-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-model/1.19.0/c0c13b04c565e4adef09c613ea0ffa6bf348050a/smithy-model-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-utils/1.19.0/2d84332b75c9700d9c00c1f5e9408d439115ab80/smithy-utils-1.19.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-gradle-plugin/0.6.0/5e9c02a25231d08ac7546b42b9e1e57cded397d2/smithy-gradle-plugin-0.6.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-cli/1.22.0/f37469296021d2ddfa90d967083e23b82234cb62/smithy-cli-1.22.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-build/1.22.0/b88577ddbc9e6f1526c7e79da54b3dff073d3476/smithy-build-1.22.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-linters/1.22.0/b961d1f8346d09a8f4851e7555b95cc48e79c4/smithy-linters-1.22.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-diff/1.22.0/1c837233c0d64c4d88da8f83a526fb351c147675/smithy-diff-1.22.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-model/1.22.0/81e1c21ce28812613b0cbd05001010cc63a0d19f/smithy-model-1.22.0.jar:/Users/jamessar/.gradle/caches/modules-2/files-2.1/software.amazon.smithy/smithy-utils/1.22.0/5d1d137137dc216663351168185eea932eafd033/smithy-utils-1.22.0.jar
Error executing Smithy CLI (thread handler)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at software.amazon.smithy.gradle.SmithyUtils.lambda$executeCliThread$2(SmithyUtils.java:305)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at software.amazon.smithy.gradle.SmithyUtils.lambda$executeCliThread$2(SmithyUtils.java:302)
Caused by: java.lang.NoSuchMethodError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$createValidator$2(ModelValidator.java:204)
	at software.amazon.smithy.model.loader.ModelAssembler.validate(ModelAssembler.java:639)
	at software.amazon.smithy.model.loader.ModelAssembler.assemble(ModelAssembler.java:556)
	at software.amazon.smithy.cli.commands.CommandUtils.buildModel(CommandUtils.java:78)
	at software.amazon.smithy.cli.commands.BuildCommand.execute(BuildCommand.java:112)
	at software.amazon.smithy.cli.Cli.run(Cli.java:144)
	at software.amazon.smithy.cli.SmithyCli.run(SmithyCli.java:91)
	at software.amazon.smithy.cli.SmithyCli.run(SmithyCli.java:82)
	... 4 more
Caused by: java.lang.NoSuchMethodError: 'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validateTrait(TraitBreakingChangesValidator.java:44)
	at software.amazon.smithy.model.validation.validators.TraitBreakingChangesValidator.validate(TraitBreakingChangesValidator.java:36)
	at software.amazon.smithy.model.loader.ModelValidator.lambda$createValidator$0(ModelValidator.java:198)
'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'
:model:smithyBuildJar (Thread[Execution worker for ':model',5,main]) completed. Took 0.229 secs.

> Configure project :server-codegen
Evaluating project ':server-codegen' using build file '/private/tmp/test/smithy-server-generator-typescript-sample/server/codegen/build.gradle'.
Found project 'project :model' as substitute for module 'software.amazon.smithy.demo:string-wizard-model'.
(detected Smithy CLI version 1.19.0)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':model:smithyBuildJar'.
> 'java.util.List software.amazon.smithy.model.traits.TraitDefinition.getBreakingChanges()'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 869ms
1 actionable task: 1 executed
Watched directory hierarchies: [/private/tmp/test/smithy-server-generator-typescript-sample, /private/tmp/smithy-server-generator-typescript-sample]
```

</details>

Any ideas why the build is failing?

**Comment by DanielBauman88** [comment]
This recently started happening to me too in a project that used to work. No changes were made.
I'm wondering if smithy libs were updated in a way that causes this - either a bug or maybe we need to upgrade other dependencies.

**Comment by adamthom-amzn** [comment]
Yes, this is an unfortunate consequence of the way dependencies are resolved by the plugin and the project itself. When Smithy does a new release, it goes to mavenCentral immediately, and will be picked up by build dependencies immediately. Unfortunately, plugin dependencies are by default loaded from jcenter, which always lags behind maven central, and so if there is an incompatibility between the jcenter and mavenCentral Smithy libraries, you get errors like this.

I will put out an update today if possible that does a better job of locking the Smithy versions.

**Comment by DanielBauman88** [comment]
Is there a fix we can use in the meantime?

**Comment by jamesls** [comment]
Is there a better place to track the underlying root cause?  I ran into the same error following the [README in awslabs/smithy-typescript](https://github.com/awslabs/smithy-typescript/blob/main/README.md).

Or if this is a fundamental issue with Smithy build itself should I create a tracking issue over on awslabs/smithy?

**Comment by adamthom-amzn** [comment]
> Is there a better place to track the underlying root cause? I ran into the same error following the [README in awslabs/smithy-typescript](https://github.com/awslabs/smithy-typescript/blob/main/README.md).
> 
> Or if this is a fundamental issue with Smithy build itself should I create a tracking issue over on awslabs/smithy?

It's an issue with the way the Smithy Gradle Plugin resolves dependencies. awslabs/smithy is probably the best place to track the underlying issue

**Comment by adamthom-amzn** [comment]
Submitted https://github.com/awslabs/smithy-typescript/pull/569 to fix the smithy-typescript README as well
